_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.7.13
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.7.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
CUDNN:
    value:
        BENCHMARK: false
        DETERMINISTIC: false
        ENABLED: false
DATASET:
    value:
        CLASS_WEIGHTS:
            - 0.5
            - 2.5
        NUM_CLASSES: 2
        ROOT: ""
        TRAIN:
            - FF_flux_1_dev
        VALID:
            - FF_flux_1_dev
GPUS:
    value:
        - 0
LOG_DIR:
    value: log
LOSS:
    value:
        LOSSES:
            - - LOC
              - 1
              - dice_entropy
        SMOOTH: 0
        USE_OHEM: false
MODEL:
    value:
        EXTRA:
            BACKBONE: mit_b2
            BN_EPS: 0.001
            BN_MOMENTUM: 0.1
            DECODER: MLPDecoder
            DECODER_EMBED_DIM: 512
            DETECTION: null
            FIX_MODULES:
                - NP++
            MODULES:
                - NP++
                - backbone
                - loc_head
            NP_WEIGHTS: pretrained_models/noiseprint++/noiseprint++.th
            PREPRC: imagenet
        MODS:
            - RGB
            - NP++
        NAME: detconfcmx
        PRETRAINED: pretrained_models/segformers/mit_b2.pth
OUTPUT_DIR:
    value: weights
TEST:
    value:
        MODEL_FILE: weights/trufor_ff_flux_1_dev/best.pth.tar
TRAIN:
    value:
        AUG: lib/config/aug_res_comp.yaml
        BATCH_SIZE_PER_GPU: 8
        BEGIN_EPOCH: 0
        END_EPOCH: 25
        EXTRA_EPOCH: 0
        IGNORE_LABEL: -1
        IMAGE_SIZE:
            - 512
            - 512
        LR: 0.005
        MOMENTUM: 0.9
        NESTEROV: false
        NUM_SAMPLES: 0
        OPTIMIZER: sgd
        PRETRAINING: null
        RESUME: true
        SHUFFLE: true
        STOP_EPOCH: -1
        WD: 0.0005
VALID:
    value:
        AUG: lib/config/aug_res_comp.yaml
        BEST_KEY: avg_p-F1_smooth
        FIRST_VALID: false
        IMAGE_SIZE: null
        MAX_SIZE: 2048
WORKERS:
    value: 8
